// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonoFlow.infrastructure.Persistance;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonoFlow.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Articulos.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FinPlan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin_plan");

                    b.Property<Guid>("IdOrden")
                        .HasColumnType("uuid")
                        .HasColumnName("id_orden");

                    b.Property<DateTime?>("InicioPlan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_plan");

                    b.Property<int>("Linea")
                        .HasColumnType("integer")
                        .HasColumnName("linea");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("referencia");

                    b.HasKey("Id")
                        .HasName("pk_articulos");

                    b.HasIndex("IdOrden", "Referencia", "Linea")
                        .IsUnique()
                        .HasDatabaseName("UK_articulo_orden_ref_linea");

                    b.ToTable("articulos", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Eventos.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("uuid")
                        .HasColumnName("id_registro");

                    b.Property<int>("IdTipoEvento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_evento");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.HasKey("Id")
                        .HasName("pk_eventos");

                    b.HasIndex("IdRegistro")
                        .HasDatabaseName("ix_eventos_id_registro");

                    b.HasIndex("IdTipoEvento")
                        .HasDatabaseName("ix_eventos_id_tipo_evento");

                    b.ToTable("eventos", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Incidencias.Incidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<Guid>("IdEvento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_evento");

                    b.Property<int>("IdTipoIncidencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_incidencia");

                    b.HasKey("Id")
                        .HasName("pk_incidencias");

                    b.HasIndex("IdEvento")
                        .HasDatabaseName("ix_incidencias_id_evento");

                    b.HasIndex("IdTipoIncidencia")
                        .HasDatabaseName("ix_incidencias_id_tipo_incidencia");

                    b.ToTable("incidencias", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Operaciones.Operacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CantidadComponentes")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_componentes");

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_total");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<Guid>("IdArticulo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_articulo");

                    b.Property<int>("IdTipoOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_operacion");

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<double?>("TiempoPlan")
                        .HasColumnType("double precision")
                        .HasColumnName("tiempo_plan");

                    b.Property<double>("TiempoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("tiempo_total");

                    b.Property<bool>("UltimaOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ultima_operacion");

                    b.HasKey("Id")
                        .HasName("pk_operaciones");

                    b.HasIndex("IdArticulo")
                        .HasDatabaseName("ix_operaciones_id_articulo");

                    b.HasIndex("IdTipoOperacion")
                        .HasDatabaseName("ix_operaciones_id_tipo_operacion");

                    b.ToTable("operaciones", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Operarios.Operario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("NumeroOperario")
                        .HasColumnType("integer")
                        .HasColumnName("numero_operario");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Operario")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_operarios");

                    b.HasIndex("NumeroOperario")
                        .IsUnique()
                        .HasDatabaseName("UK_operario_numero");

                    b.ToTable("operarios", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Ordenes.Orden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cliente")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliente");

                    b.Property<string>("CodigoProcedencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_procedencia");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IdNavision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_navision");

                    b.HasKey("Id")
                        .HasName("pk_ordenes");

                    b.HasIndex("IdNavision")
                        .IsUnique()
                        .HasDatabaseName("UK_orden_navision");

                    b.ToTable("ordenes", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Producciones.Produccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CantidadOk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cantidad_ok");

                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("uuid")
                        .HasColumnName("id_registro");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_producciones");

                    b.HasIndex("IdRegistro")
                        .HasDatabaseName("ix_producciones_id_registro");

                    b.ToTable("producciones", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.ProduccionesRechazadas.Rechazo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CantidadRechazo")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_rechazo");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comentario");

                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("uuid")
                        .HasColumnName("id_registro");

                    b.Property<int>("IdTipoRechazo")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_rechazo");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_rechazos");

                    b.HasIndex("IdRegistro")
                        .HasDatabaseName("ix_rechazos_id_registro");

                    b.HasIndex("IdTipoRechazo")
                        .HasDatabaseName("ix_rechazos_id_tipo_rechazo");

                    b.ToTable("rechazos", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.RegistrosTrabajo.RegistroTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<bool>("Finalizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("finalizado");

                    b.Property<Guid>("IdOperacion")
                        .HasColumnType("uuid")
                        .HasColumnName("id_operacion");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<Guid?>("OperacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("operacion_id");

                    b.Property<int>("TotalProducidoOk")
                        .HasColumnType("integer")
                        .HasColumnName("total_producido_ok");

                    b.Property<int>("TotalRechazado")
                        .HasColumnType("integer")
                        .HasColumnName("total_rechazado");

                    b.HasKey("Id")
                        .HasName("pk_registros_trabajo");

                    b.HasIndex("IdOperacion")
                        .HasDatabaseName("ix_registros_trabajo_id_operacion");

                    b.HasIndex("OperacionId")
                        .HasDatabaseName("ix_registros_trabajo_operacion_id");

                    b.ToTable("registros_trabajo", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.SesionesOperarios.SesionOperario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<Guid>("IdOperario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_operario");

                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("uuid")
                        .HasColumnName("id_registro");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.HasKey("Id")
                        .HasName("pk_sesiones_operarios");

                    b.HasIndex("IdOperario")
                        .HasDatabaseName("ix_sesiones_operarios_id_operario");

                    b.HasIndex("IdRegistro")
                        .HasDatabaseName("ix_sesiones_operarios_id_registro");

                    b.ToTable("sesiones_operarios", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.TiposEvento.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_tipos_evento");

                    b.ToTable("tipos_evento", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.TiposIncidencia.TipoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_tipos_incidencia");

                    b.ToTable("tipos_incidencia", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.TiposOperacion.TipoOperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_tipos_operacion");

                    b.ToTable("tipos_operacion", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.TiposRechazo.TipoRechazo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motivo");

                    b.HasKey("Id")
                        .HasName("pk_tipos_rechazo");

                    b.ToTable("tipos_rechazo", "public");
                });

            modelBuilder.Entity("MonoFlow.infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.ToTable("outbox_message", "public");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Articulos.Articulo", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.Ordenes.Orden", null)
                        .WithMany("Articulos")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_ordenes_id_orden");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Eventos.Evento", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.RegistrosTrabajo.RegistroTrabajo", null)
                        .WithMany("Eventos")
                        .HasForeignKey("IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_registros_trabajo_id_registro");

                    b.HasOne("MonoFlow.domain.Aggregates.TiposEvento.TipoEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("IdTipoEvento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_tipos_evento_id_tipo_evento");

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Incidencias.Incidencia", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.Eventos.Evento", null)
                        .WithMany("Incidencias")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidencias_eventos_id_evento");

                    b.HasOne("MonoFlow.domain.Aggregates.TiposIncidencia.TipoIncidencia", "TipoIncidencia")
                        .WithMany()
                        .HasForeignKey("IdTipoIncidencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incidencias_tipos_incidencia_id_tipo_incidencia");

                    b.Navigation("TipoIncidencia");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Operaciones.Operacion", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.Articulos.Articulo", null)
                        .WithMany("Operaciones")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_operacion_articulo");

                    b.HasOne("MonoFlow.domain.Aggregates.TiposOperacion.TipoOperacion", "TipoOperacion")
                        .WithMany()
                        .HasForeignKey("IdTipoOperacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_operacion_tipo");

                    b.Navigation("TipoOperacion");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Producciones.Produccion", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.RegistrosTrabajo.RegistroTrabajo", null)
                        .WithMany("Producciones")
                        .HasForeignKey("IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_producciones_registros_trabajo_id_registro");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.ProduccionesRechazadas.Rechazo", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.RegistrosTrabajo.RegistroTrabajo", null)
                        .WithMany("Rechazos")
                        .HasForeignKey("IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rechazos_registros_trabajo_id_registro");

                    b.HasOne("MonoFlow.domain.Aggregates.TiposRechazo.TipoRechazo", "TipoRechazo")
                        .WithMany()
                        .HasForeignKey("IdTipoRechazo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_rechazadas_tipo");

                    b.Navigation("TipoRechazo");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.RegistrosTrabajo.RegistroTrabajo", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.Operaciones.Operacion", null)
                        .WithMany()
                        .HasForeignKey("IdOperacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registros_trabajo_operaciones_id_operacion");

                    b.HasOne("MonoFlow.domain.Aggregates.Operaciones.Operacion", null)
                        .WithMany("Registros")
                        .HasForeignKey("OperacionId")
                        .HasConstraintName("fk_registros_trabajo_operaciones_operacion_id");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.SesionesOperarios.SesionOperario", b =>
                {
                    b.HasOne("MonoFlow.domain.Aggregates.Operarios.Operario", "Operario")
                        .WithMany()
                        .HasForeignKey("IdOperario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_sesion_operario");

                    b.HasOne("MonoFlow.domain.Aggregates.RegistrosTrabajo.RegistroTrabajo", null)
                        .WithMany("Sesiones")
                        .HasForeignKey("IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sesiones_operarios_registros_trabajo_id_registro");

                    b.Navigation("Operario");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Articulos.Articulo", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Eventos.Evento", b =>
                {
                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Operaciones.Operacion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.Ordenes.Orden", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("MonoFlow.domain.Aggregates.RegistrosTrabajo.RegistroTrabajo", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Producciones");

                    b.Navigation("Rechazos");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
